# Make sure provider-helm has enough permissions to install your chart into cluster
#
# You can give admin permissions by running:
# SA=$(kubectl -n upbound-system get sa -o name | grep provider-helm | sed -e 's|serviceaccount\/|upbound-system:|g')
# kubectl create clusterrolebinding provider-helm-admin-binding --clusterrole cluster-admin --serviceaccount="${SA}"
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-in-cluster
spec:
  credentials:
    source: InjectedIdentity
